apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   service: backend-chaos
 name: backend-chaos
spec:
 replicas: 1
 selector:
  matchLabels:
    service: backend-chaos
 template:
   metadata:
     labels:
       service: backend-chaos
   spec:
     containers:
     - image: mfathy89/udagram-chaos-service
       name: udagram-chaos-service
       imagePullPolicy: Always 
       resources:
         requests:
           memory: "64Mi"
           cpu: "250m"
         limits:
           memory: "512Mi"
           cpu: "500m"                 
       env:
       - name: POSTGRES_DB
         valueFrom:
           configMapKeyRef:
             name: env-config
             key: POSTGRES_DB
       - name: POSTGRES_HOST
         valueFrom:
           configMapKeyRef:
             name: env-config
             key: POSTGRES_HOST
       - name: POSTGRES_PASSWORD
         valueFrom:
           configMapKeyRef:
             name: env-config
             key: POSTGRES_PASSWORD
       - name: POSTGRES_USERNAME
         valueFrom:
           configMapKeyRef:
             name: env-config
             key: POSTGRES_USERNAME
     restartPolicy: Always